feature/a1
ArtyomTsirsis/JavaAndMagic pull request #19
Opened 2022-03-14 13:11 UTC by ArtyomTsirsis

2022-03-19 08:14 UTC, nextlevelplay approved these changes

2022-03-19 08:27 UTC, nextlevelplay commented on src/main/java/com/game/repository/hero/HeroRepository.java
>  public class HeroRepository {
Сразу не заметил, у тебя HeroRepository - это класс не имплементирующий интерфейс - что приводит к жёсткой связке в наших сервисах! Надо создать интрефейс и  Именно его предавать в сервисы. Когда подключишь настоящую базу, всё что тебе нужно будет сделать - это снять с этого репозитория аннотацию и поставить её на настоящую.

2022-03-19 08:30 UTC, nextlevelplay commented on src/main/java/com/game/repository/hero/HeroRepository.java
>  public class HeroRepository {
Типо такого RealDataBase implement Repository (где Репозиторий - это интерфейс), иду в сервисы, чтобы развить мысль...

2022-03-19 08:36 UTC, nextlevelplay commented on src/main/java/com/game/repository/services/CreateHeroService.java
> +    private HeroRepository repository;
Именно про это я и говорил - в игре пропадёт HeroRepository - а сервис будет настырно искать его...
Но если ты сделаешь вот так:
@Autowired
private Repository repository;   Сервису абсолютно будет наплевать какая реализация к нему пришла - на массиве или настоящая база. В твоём случае он будет искать на массиве - так как она жёстко привязана.
и чтобы это исправить придётся переколбасить все сервисы в ручную. Главное, чтобы небыло две имплементации и с анотациями в одно время, так как они превратятся в Beans и Spring выдаст ошибку, что нащёл сразу два файла с реализацией репозитория(Ну или можно как ты навесить @Qualifier - но это опять лишний код).

2022-03-19 08:41 UTC, nextlevelplay requested changes

2022-03-19 08:41 UTC, nextlevelplay commented on src/main/java/com/game/repository/services/CreateHeroService.java
> +    private HeroRepository repository;
Сорян, наверника - это можно было пофиксить раньше, но я просто мерджил не вникая в код.

2022-03-24 18:17 UTC, ArtyomTsirsis commented
Repo interface сделал.

2022-03-24 18:23 UTC, nextlevelplay approved these changes

2022-03-24 18:23 UTC, merged