Updated CRUD UI actions. except Adventure
ArtyomTsirsis/JavaAndMagic pull request #27
Opened 2022-04-05 16:56 UTC by nextlevelplay

2022-04-05 22:00 UTC, ArtyomTsirsis commented on src/main/java/com/game/ui/DeleteByIdUIAction.java
> +            var checkIfHeroExist = findHeroByNameService.findByName(heroName);
А зачем так сложно? Ты сначала ищешь героя по ключу, но от результата ничего не зависит, ты просто его достаешь. Потом ты удаляешь героя и выводя на консоль, у найденого героя ты достаешь имя. Почему бы не пропустить лаг с поиском и на консоль выводить сразу имя, по которому ты искал и удалял?

2022-04-05 22:02 UTC, ArtyomTsirsis requested changes
Comment in delete method.

2022-04-06 04:48 UTC, nextlevelplay commented on src/main/java/com/game/ui/DeleteByIdUIAction.java
> +            var checkIfHeroExist = findHeroByNameService.findByName(heroName);
> А зачем так сложно? Ты сначала ищешь героя по ключу, но от результата ничего не зависит
Принципе зависит, если такого героя нету - потому, что ошиблись буквой или его нет в базе будет ошибка NoSuchObjectException и программа не пойдёт дальше.
А если всё хорошо, то удалит героя. 

> у найденого героя ты достаешь имя. Почему бы не пропустить лаг с поиском и на консоль выводить сразу имя, по которому ты искал и удалял?
Если ты про  +heroName, то да можно и так. Я не подумал что будет какой-то лаг. У меня всё нормально работает

2022-04-06 07:22 UTC, ArtyomTsirsis commented on src/main/java/com/game/ui/DeleteByIdUIAction.java
> +            var checkIfHeroExist = findHeroByNameService.findByName(heroName);
Я тогда лучше добавлю в делит сервис валидацию и пусть он кидает эксепшн. Это будет правильнее, чем тебе делать вот так. Эта строчка и дополнительная переменная выглядят не очень. )

2022-04-06 13:41 UTC, ArtyomTsirsis requested changes
Сделай тогда без findBy. Я со своей стороны закину изменения в сервис.

2022-04-08 16:22 UTC, ArtyomTsirsis approved these changes

2022-04-08 16:22 UTC, merged