delete unusable content/ small repacking
ArtyomTsirsis/JavaAndMagic pull request #48
Opened 2022-05-26 12:47 UTC by Denteron

2022-05-26 17:46 UTC, ArtyomTsirsis requested changes
@Denteron

2022-05-26 19:11 UTC, Denteron commented
@ArtyomTsirsis перезалил тесты на батл контроллер, они могут иногда ловить пробку и ругаться на "кракозябру" которую он создает при переводе с русского :) Но тут уж только все описания на англ переходить :)

2022-05-27 09:42 UTC, Denteron commented
@ArtyomTsirsis 
Может вылезти - error: unmappable character (0x98) for encoding windows-1251
                                    "output": "Р�?С‹СЃС‚СЂР°СЏ Р°С‚Р°РєР°"
но это из-за русского языка в описаниях :)

2022-05-27 10:57 UTC, ArtyomTsirsis approved these changes

2022-05-27 10:57 UTC, merged